apiVersion: v1
kind: ReplicationController
metadata:
  name: product-mocker
  namespace: brizo
  labels:
    brizoManaged: "true"
    appUUID: abc123
spec:
  replicas: 3
  selector:
    appUUID: abc123
  template:
    metadata:
      labels:
        brizoManaged: "true"
        appUUID: abc123
    spec:
      containers:
        - name: app
          image: nexmill/mock-go-api:latest
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8000
      restartPolicy: Always
      dnsPolicy: ClusterFirst
